import type { Book } from '@/lib/types';

export const MOCK_BOOKS: Book[] = [
  {
    id: 1,
    title: 'Dune',
    author: 'Frank Herbert',
    summary: 'A mythic and emotionally charged hero\'s journey, Dune tells the story of Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding...',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Science Fiction'],
    themes: ['politics', 'ecology', 'religion', 'adventure', 'chosen one'],
    rating: 4.8,
    amazonLink: 'https://www.amazon.com/s?k=Dune+Frank+Herbert',
  },
  {
    id: 2,
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    summary: 'The story of the five Bennet sisters and their search for love and marriage in 19th-century England.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Romance', 'Literary Fiction'],
    themes: ['love', 'class', 'society', 'family'],
    rating: 4.7,
    amazonLink: 'https://www.amazon.com/s?k=Pride+and+Prejudice+Jane+Austen',
  },
  {
    id: 3,
    title: 'The Hobbit',
    author: 'J.R.R. Tolkien',
    summary: 'A reluctant hobbit, Bilbo Baggins, sets out to the Lonely Mountain with a spirited group of dwarves to reclaim their mountain home, and a dragon\'s treasure.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Fantasy'],
    themes: ['adventure', 'quest', 'friendship', 'courage'],
    rating: 4.9,
    amazonLink: 'https://www.amazon.com/s?k=The+Hobbit+JRR+Tolkien',
  },
  {
    id: 4,
    title: 'Sapiens: A Brief History of Humankind',
    author: 'Yuval Noah Harari',
    summary: 'A groundbreaking narrative of humanity’s creation and evolution—a #1 international bestseller that explores the ways in which biology and history have defined us.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Non-Fiction', 'Biography'],
    themes: ['history', 'evolution', 'society', 'science'],
    rating: 4.6,
    amazonLink: 'https://www.amazon.com/s?k=Sapiens+A+Brief+History+of+Humankind+Yuval+Noah+Harari',
  },
  {
    id: 5,
    title: 'The Silent Patient',
    author: 'Alex Michaelides',
    summary: 'A shocking psychological thriller of a woman’s act of violence against her husband—and of the therapist obsessed with uncovering her motive.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Thriller', 'Mystery'],
    themes: ['psychology', 'secrets', 'suspense', 'obsession'],
    rating: 4.5,
    amazonLink: 'https://www.amazon.com/s?k=The+Silent+Patient+Alex+Michaelides',
  },
  {
    id: 6,
    title: 'Project Hail Mary',
    author: 'Andy Weir',
    summary: 'Ryland Grace is the sole survivor on a desperate, last-chance mission—and if he fails, humanity and the earth itself will perish.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Science Fiction'],
    themes: ['space travel', 'problem solving', 'aliens', 'humor'],
    rating: 4.8,
    amazonLink: 'https://www.amazon.com/s?k=Project+Hail+Mary+Andy+Weir',
  },
  {
    id: 7,
    title: 'Circe',
    author: 'Madeline Miller',
    summary: 'In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child - not powerful, like her father, nor viciously alluring like her mother.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Fantasy', 'Historical Fiction'],
    themes: ['mythology', 'magic', 'strong female protagonist', 'transformation'],
    rating: 4.7,
    amazonLink: 'https://www.amazon.com/s?k=Circe+Madeline+Miller',
  },
  {
    id: 8,
    title: 'The Da Vinci Code',
    author: 'Dan Brown',
    summary: 'A murder inside the Louvre, and clues in Da Vinci paintings, lead to the discovery of a religious mystery protected by a secret society for two thousand years.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Thriller', 'Mystery'],
    themes: ['conspiracy', 'history', 'puzzles', 'secrets'],
    rating: 4.4,
    amazonLink: 'https://www.amazon.com/s?k=The+Da+Vinci+Code+Dan+Brown',
  },
  {
    id: 9,
    title: 'Educated: A Memoir',
    author: 'Tara Westover',
    summary: 'An unforgettable memoir about a young girl who, kept out of school, leaves her survivalist family and goes on to earn a PhD from Cambridge University.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Biography', 'Non-Fiction'],
    themes: ['family', 'education', 'resilience', 'transformation'],
    rating: 4.8,
    amazonLink: 'https://www.amazon.com/s?k=Educated+A+Memoir+Tara+Westover',
  },
  {
    id: 10,
    title: 'The Seven Husbands of Evelyn Hugo',
    author: 'Taylor Jenkins Reid',
    summary: 'Aging and reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Historical Fiction', 'Romance'],
    themes: ['fame', 'secrets', 'love', 'hollywood', 'strong female protagonist'],
    rating: 4.7,
    amazonLink: 'https://www.amazon.com/s?k=The+Seven+Husbands+of+Evelyn+Hugo+Taylor+Jenkins+Reid',
  },
  {
    id: 11,
    title: 'A Court of Thorns and Roses',
    author: 'Sarah J. Maas',
    summary: 'When nineteen-year-old huntress Feyre kills a wolf in the woods, a beast-like creature arrives to demand retribution for it.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Fantasy', 'Romance'],
    themes: ['fae', 'magic', 'love', 'adventure'],
    rating: 4.6,
    amazonLink: 'https://www.amazon.com/s?k=A+Court+of+Thorns+and+Roses+Sarah+J+Maas',
  },
  {
    id: 12,
    title: 'The Shining',
    author: 'Stephen King',
    summary: 'Jack Torrance’s new job at the Overlook Hotel is the perfect chance for a fresh start. But as the harsh winter weather sets in, the idyllic location feels ever more remote...and more sinister.',
    coverImage: 'https://placehold.co/300x450.png',
    genres: ['Horror', 'Thriller'],
    themes: ['supernatural', 'isolation', 'madness', 'family'],
    rating: 4.7,
    amazonLink: 'https://www.amazon.com/s?k=The+Shining+Stephen+King',
  },
];
